# Generated by Django 5.2.3 on 2025-06-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0002_user_description_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
