# Generated by Django 5.2.3 on 2025-06-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
