# Generated by Django 5.1.6 on 2025-06-29 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_courselimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselimit',
            name='limit',
            field=models.IntegerField(default=0, verbose_name='maximum student'),
        ),
        migrations.AddField(
            model_name='courselimit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
